import { env } from 'cloudflare:workers'
import { getRequest } from '@tanstack/react-start/server'

import { parseMembers, type Member } from '../lib/members'
import { securityHeadersInit } from '../lib/securityHeaders'
import { authenticateRequest } from './auth'

/** Reads secret MEMBERS. Empty when unset (the display becomes the local part of the e-mail, in gray) */
export function allMembers(): Member[] {
  // MEMBERS appears in the types generated by cf-typegen only when .dev.vars exists (on a
  // local machine without it, it does not exist in the types), so the type is loosened only
  // here instead of going through any. The value itself is a wrangler secret and is always
  // string | undefined.
  return parseMembers((env as unknown as { MEMBERS?: string }).MEMBERS)
}

/**
 * The e-mail of the actor. The global middleware (src/start.ts) enforces authentication
 * before execution gets here, so in theory the failure side is never entered. Re-verifying
 * the JWT on every call is wasteful (improvement candidate for Phase 2: consume the
 * middleware context and stop the double verification), but this errs on the safe side
 * rather than writing rows as 'unknown'.
 */
export async function currentActorEmail(): Promise<string> {
  const result = await authenticateRequest(getRequest())
  if (!result.ok) {
    throw new Response('ログインが必要です。', {
      status: 403,
      headers: securityHeadersInit({ 'content-type': 'text/plain; charset=utf-8' }),
    })
  }
  return result.identity.email
}
