/**
 * Lists every video of the vendors' YouTube channels with yt-dlp and turns them into SQL.
 *
 *   npm run import:channel-videos               # uses the cached lists when there are any
 *   npm run import:channel-videos -- --refresh  # asks YouTube again
 *
 * Needs yt-dlp on PATH (brew install yt-dlp). Which channels are read is in
 * seed.local/channel-videos.json (gitignored: it is real data):
 *   { "channels": [{ "channelId": "UC…", "name": "…", "vendorId": "<vendors.id or null>" }] }
 *
 * Output: seed.local/out/channel-videos-YYYYMMDD.sql. The owner runs it against the production D1:
 *   npx wrangler d1 execute sumai-log --remote --file seed.local/out/channel-videos-YYYYMMDD.sql
 * The upsert is keyed by video_id, so re-running is safe (watched flags are kept). Titles are
 * never printed, only counts.
 */
import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import {
  CHANNEL_TABS,
  channelVideoUpsertSql,
  channelVideosOf,
  parseChannelsConfig,
  parseFlatPlaylist,
} from '../src/lib/channelVideos/import.ts'
import { toJstDateKey } from '../src/lib/jst.ts'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const CONFIG_PATH = resolve(root, 'seed.local/channel-videos.json')
const CACHE_DIR = resolve(root, 'seed.local/cache/channel-videos')
const OUT_DIR = resolve(root, 'seed.local/out')

const refresh = process.argv.includes('--refresh')

/** One tab of one channel as yt-dlp prints it; `null` when the channel has no such tab */
function loadTab(channelId: string, tab: string): unknown {
  const cachePath = resolve(CACHE_DIR, `${channelId}-${tab}.json`)
  if (!refresh && existsSync(cachePath)) return JSON.parse(readFileSync(cachePath, 'utf8'))
  let out: string
  try {
    out = execFileSync(
      'yt-dlp',
      [
        '--flat-playlist',
        '--sleep-requests',
        '1',
        // Without these YouTube sends machine-translated English titles
        '--extractor-args',
        'youtube:lang=ja',
        '--add-header',
        'Accept-Language:ja-JP,ja;q=0.9',
        '-J',
        `https://www.youtube.com/channel/${channelId}/${tab}`,
      ],
      { encoding: 'utf8', maxBuffer: 256 * 1024 * 1024, stdio: ['ignore', 'pipe', 'ignore'] },
    )
  } catch {
    // yt-dlp exits non-zero for a tab the channel does not have
    out = 'null'
  }
  writeFileSync(`${cachePath}.tmp`, out)
  renameSync(`${cachePath}.tmp`, cachePath)
  return JSON.parse(out)
}

function main() {
  if (!existsSync(CONFIG_PATH)) {
    console.error(
      'Missing seed.local/channel-videos.json. Create it as:\n' +
        '{ "channels": [{ "channelId": "UC…", "name": "…", "vendorId": null }] }',
    )
    process.exit(1)
  }
  const channels = parseChannelsConfig(JSON.parse(readFileSync(CONFIG_PATH, 'utf8')))
  mkdirSync(CACHE_DIR, { recursive: true })
  mkdirSync(OUT_DIR, { recursive: true })

  // No BEGIN / COMMIT: `wrangler d1 execute --file` already runs the file atomically
  const lines = ['-- generated by scripts/import-channel-videos.ts']
  for (const channel of channels) {
    const tabs = CHANNEL_TABS.map(({ tab, kind }) => ({
      kind,
      entries: parseFlatPlaylist(loadTab(channel.channelId, tab)),
    }))
    const videos = channelVideosOf(channel, tabs)
    for (const video of videos) lines.push(channelVideoUpsertSql(video, crypto.randomUUID()))
    const perKind = tabs.map(({ kind, entries }) => `${kind} ${entries.length}`).join(', ')
    console.log(`${channel.channelId}: ${videos.length} videos (${perKind})`)
  }

  const stamp = toJstDateKey(new Date().toISOString()).replaceAll('-', '')
  const outPath = resolve(OUT_DIR, `channel-videos-${stamp}.sql`)
  writeFileSync(outPath, `${lines.join('\n')}\n`)
  console.log(`wrote ${lines.length - 1} statements to ${outPath}`)
}

main()
