/**
 * 過去分のメルマガ（Gmail Takeout の mbox）を SQL にする一回きりのスクリプト（設計 2026-09-19 §6）。
 *
 *   npm run import:mbox -- seed.local/mail.mbox --vendors seed.local/out/vendors.json
 *
 * vendors.json は `npx wrangler d1 execute sumai-log --remote --json --command
 *   "SELECT id, name, news_email_domain FROM vendors"` の出力をそのまま保存したもの。
 * 出力 seed.local/out/mails.sql は冪等（message_id / url の重複は DO NOTHING）。
 * 本文・アドレスは標準出力に出さない（集計だけ）。
 *
 * 再実行は想定しない（一回きり）。既に未割当で入った行に後から業者ドメインが付いた場合は
 * 設定ページの「取り込む」を使う（再実行すると vendor_news が新しい mail_id を参照して孤立する）。
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import PostalMime from 'postal-mime'

import { toJstDateKey } from '../src/lib/jst.ts'
import { splitForwardedBlock } from '../src/lib/mail/forwarded.ts'
import { matchVendorByDomain } from '../src/lib/mail/match.ts'
import { splitMbox } from '../src/lib/mail/mbox.ts'
import { extractBody, toParsedMail } from '../src/lib/mail/parse.ts'
import { inboundToNews } from '../src/lib/mail/toNews.ts'
import { sqlString } from './lib/seed.mjs'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')

type VendorRow = { id: string; name: string; news_email_domain: string | null }

function parseArgs(argv: string[]): { mbox: string; vendors: string } {
  const mbox = argv.find((a) => !a.startsWith('--'))
  const vi = argv.indexOf('--vendors')
  const vendors = vi >= 0 ? argv[vi + 1] : undefined
  if (!mbox || !vendors) {
    console.error('usage: tsx scripts/import-mbox.ts <mail.mbox> --vendors <vendors.json>')
    process.exit(1)
  }
  return { mbox: resolve(root, mbox), vendors: resolve(root, vendors) }
}

function loadVendors(path: string): { id: string; name: string; newsEmailDomain: string | null }[] {
  const json = JSON.parse(readFileSync(path, 'utf8')) as { results?: VendorRow[] }[] | VendorRow[]
  const rows: VendorRow[] =
    Array.isArray(json) && json.length > 0 && 'results' in json[0]
      ? (json as { results?: VendorRow[] }[]).flatMap((r) => r.results ?? [])
      : (json as VendorRow[])
  return rows.map((r) => ({ id: r.id, name: r.name, newsEmailDomain: r.news_email_domain }))
}

async function main() {
  const { mbox, vendors: vendorsPath } = parseArgs(process.argv.slice(2))
  const vendors = loadVendors(vendorsPath)
  // latin1（1 バイト = 1 コードユニット）で読む: mbox には Shift_JIS のような 8 ビットの
  // 本文がそのまま入っていることがあり、utf8 として読むと壊れた時点で復元できなくなる。
  // 区切り（'From ' 行）は ASCII なので分割は文字列のままで正しく、各メッセージは
  // Buffer.from(part, 'latin1') でバイト列に戻して postal-mime に渡す（charset の
  // 解釈は postal-mime に任せる）。
  const messages = splitMbox(readFileSync(mbox, 'latin1'))
  const nowIso = new Date().toISOString()
  const receivedOn = toJstDateKey(nowIso)

  // BEGIN TRANSACTION / COMMIT は付けない: `wrangler d1 execute --file` は既にファイル全体を
  // atomic に実行するため、トランザクション文を足すと「トランザクション内でトランザクションを
  // 開始した」エラーになる（Cloudflare D1 のインポート手順どおり）。
  const lines: string[] = ['-- generated by scripts/import-mbox.ts']
  const perVendor = new Map<string, number>()
  let unassigned = 0
  let withEvent = 0

  for (const raw of messages) {
    const email = await PostalMime.parse(Buffer.from(raw, 'latin1'))
    const parsed = await toParsedMail(email)
    // mbox は本人の Takeout（信頼できる入力）なので無条件に本文を作る
    // （Worker 側は認可が通ってからだけ呼ぶ。src/lib/mail/parse.ts の extractBody 参照）
    const body = extractBody(email)
    let fromAddress = parsed.from
    let subject = parsed.subject
    let sentOn = parsed.date ? toJstDateKey(parsed.date) : null
    let bodyText = body.text
    const block = splitForwardedBlock(body.text)
    if (block) {
      fromAddress = block.from ?? fromAddress
      subject = block.subject ?? subject
      sentOn = block.date ?? sentOn
      bodyText = block.body
    }
    // NUL は SQLite の TEXT に入らない（sqlite3_bind_text が NUL で切れる）ので取り除く
    subject = subject.replace(/\0/g, '')
    // 同上（本文）
    bodyText = bodyText.replace(/\0/g, '')
    const vendor = matchVendorByDomain(fromAddress, vendors)
    const mailId = crypto.randomUUID()
    const status = vendor ? 'imported' : 'unassigned'
    let newsId: string | null = null
    let newsSql: string | null = null
    let newsUrl: string | null = null
    if (vendor) {
      const draft = inboundToNews(
        { messageId: parsed.messageId, subject, text: bodyText, sentOn },
        vendor.id,
        receivedOn,
      )
      newsId = crypto.randomUUID()
      newsUrl = draft.url
      newsSql =
        `INSERT INTO vendor_news (id, vendor_id, url, title, summary, published_on, event_start, event_end, event_kind, mail_id) VALUES (` +
        [
          newsId,
          draft.vendorId,
          draft.url,
          draft.title,
          draft.summary,
          draft.publishedOn,
          draft.eventStart,
          draft.eventEnd,
          draft.eventKind,
          mailId,
        ]
          .map(sqlString)
          .join(', ') +
        `) ON CONFLICT(url) DO NOTHING;`
      perVendor.set(vendor.name, (perVendor.get(vendor.name) ?? 0) + 1)
      if (draft.eventStart) withEvent++
    } else {
      unassigned++
    }
    lines.push(
      `INSERT INTO inbound_mails (id, message_id, received_at, from_address, forwarded_by, subject, sent_on, body_text, body_truncated, status, reject_reason, vendor_id, news_id, created_at, updated_at) VALUES (` +
        [
          mailId,
          parsed.messageId,
          nowIso,
          fromAddress,
          'mbox',
          subject,
          sentOn,
          bodyText,
          body.truncated ? 1 : 0,
          status,
          null,
          vendor?.id ?? null,
          // news_id はこの時点では NULL。vendor_news の INSERT の後に UPDATE で付ける
          // （inbound_mails.news_id → vendor_news と vendor_news.mail_id → inbound_mails は
          // 相互に FK なので、先に news_id を入れると FK 違反で全文が巻き戻る）
          null,
          nowIso,
          nowIso,
        ]
          .map(sqlString)
          .join(', ') +
        `) ON CONFLICT(message_id) DO NOTHING;`,
    )
    if (newsSql && newsId) {
      lines.push(newsSql)
      // 再実行で vendor_news が DO NOTHING になった場合も、url から既存の id を引いて紐づける
      lines.push(
        `UPDATE inbound_mails SET news_id = (SELECT id FROM vendor_news WHERE url = ${sqlString(newsUrl)}) WHERE id = ${sqlString(mailId)} AND news_id IS NULL;`,
      )
    }
  }

  const out = resolve(root, 'seed.local/out/mails.sql')
  mkdirSync(dirname(out), { recursive: true })
  writeFileSync(out, lines.join('\n') + '\n')

  console.log(`mails: ${messages.length} 通 → ${out}`)
  for (const [name, n] of perVendor) console.log(`  ${name}: ${n}`)
  console.log(`  未割当: ${unassigned}`)
  console.log(`  日程あり: ${withEvent}`)
  console.log('次: npx wrangler d1 execute sumai-log --remote --file seed.local/out/mails.sql')
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : String(e))
  process.exit(1)
})
