/**
 * Reads the built examples on the vendors' sites and turns them into SQL
 * (docs/superpowers/specs/2026-10-01-works-list-design.md §4).
 *
 *   npm run import:works            # uses the cached pages when there are any
 *   npm run import:works -- --refresh   # fetches every page again
 *
 * Which sites are read is in seed.local/works-sites.json (gitignored: it is real data):
 *   { "sites": [{ "key": "siteA", "parser": "siteA", "listUrl": "https://...", "vendorId": "<vendors.id or null>" }] }
 *
 * Output: seed.local/out/works-YYYYMMDD.sql. The owner runs it against the production D1:
 *   npx wrangler d1 execute sumai-log --remote --file seed.local/out/works-YYYYMMDD.sql
 * The upsert is keyed by source_url, so re-running is safe (watched flags and videos pasted by
 * hand are kept). Titles and values are never printed, only counts.
 */
import { createHash } from 'node:crypto'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { parseSitesConfig } from '../src/lib/works/config.ts'
import { crawlSite } from '../src/lib/works/crawl.ts'
import { siteA } from '../src/lib/works/siteA.ts'
import { siteB } from '../src/lib/works/siteB.ts'
import { siteC } from '../src/lib/works/siteC.ts'
import { workUpsertSql } from '../src/lib/works/sql.ts'
import type { ParsedWork } from '../src/lib/works/types.ts'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const CONFIG_PATH = resolve(root, 'seed.local/works-sites.json')
const CACHE_DIR = resolve(root, 'seed.local/cache/works')
const OUT_DIR = resolve(root, 'seed.local/out')
const PARSERS = { siteA, siteB, siteC }

/** Pause between two network requests: these are small sites, read them slowly and one at a time */
const REQUEST_GAP_MS = 1000
const REQUEST_TIMEOUT_MS = 30_000
const USER_AGENT = 'Mozilla/5.0 (sumai-log works import; personal use)'

const refresh = process.argv.includes('--refresh')
let lastRequestAt = 0

async function load(url: string): Promise<string> {
  const cachePath = resolve(CACHE_DIR, `${createHash('sha1').update(url).digest('hex')}.html`)
  if (!refresh && existsSync(cachePath)) return readFileSync(cachePath, 'utf8')

  const wait = lastRequestAt + REQUEST_GAP_MS - Date.now()
  if (wait > 0) await new Promise((done) => setTimeout(done, wait))
  lastRequestAt = Date.now()

  const res = await fetch(url, {
    headers: { 'user-agent': USER_AGENT },
    signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
  })
  if (!res.ok) throw new Error(`HTTP ${res.status}`)
  const html = new TextDecoder('utf-8').decode(await res.arrayBuffer())
  writeFileSync(cachePath, html)
  return html
}

function countFilled(works: ParsedWork[]) {
  const has = (pick: (w: ParsedWork) => unknown) => works.filter((w) => pick(w) != null).length
  return {
    works: works.length,
    video: has((w) => w.youtubeVideoId),
    points: works.filter((w) => w.points.length > 0).length,
    ua: has((w) => w.uaValue),
    c: has((w) => w.cValue),
    family: has((w) => w.family),
    floorArea: has((w) => w.floorAreaTsubo),
    layout: has((w) => w.layout),
    completedOn: has((w) => w.completedOn),
  }
}

async function main() {
  if (!existsSync(CONFIG_PATH)) {
    console.error(
      'Missing seed.local/works-sites.json. Create it as:\n' +
        '{ "sites": [{ "key": "siteA", "parser": "siteA", "listUrl": "https://...", "vendorId": null }] }',
    )
    process.exit(1)
  }
  const sites = parseSitesConfig(JSON.parse(readFileSync(CONFIG_PATH, 'utf8')))
  for (const site of sites) {
    if (site.vendorId === null) {
      console.warn(
        `warning: ${site.key} has no vendorId; its works will show no company name and no company filter`,
      )
    }
  }
  mkdirSync(CACHE_DIR, { recursive: true })
  mkdirSync(OUT_DIR, { recursive: true })

  // No BEGIN / COMMIT: `wrangler d1 execute --file` already runs the file atomically
  const lines = ['-- generated by scripts/import-works.ts']
  let failedCount = 0

  for (const site of sites) {
    const { works, failed } = await crawlSite(site, PARSERS[site.parser], load)
    for (const work of works) lines.push(workUpsertSql(work, crypto.randomUUID()))
    failedCount += failed.length
    console.log(
      `${site.key}:`,
      JSON.stringify(countFilled(works)),
      `failed pages: ${failed.length}`,
    )
    // The urls are real data but stay on the owner's terminal; they are needed to retry
    for (const url of failed) console.log(`  failed: ${url}`)
  }

  const stamp = new Date().toISOString().slice(0, 10).replaceAll('-', '')
  const outPath = resolve(OUT_DIR, `works-${stamp}.sql`)
  writeFileSync(outPath, `${lines.join('\n')}\n`)
  console.log(`wrote ${lines.length - 1} statements to ${outPath}`)
  if (failedCount > 0) process.exit(1)
}

await main()
