/**
 * One-off script that turns past newsletters (a Gmail Takeout mbox) into SQL
 * (design 2026-09-19 §6).
 *
 *   npm run import:mbox -- seed.local/mail.mbox --vendors seed.local/out/vendors.json
 *
 * vendors.json is the output of `npx wrangler d1 execute sumai-log --remote --json --command
 *   "SELECT id, name, news_email_domain FROM vendors"` saved as is.
 * The output seed.local/out/mails.sql is idempotent (duplicate message_id / url is DO NOTHING).
 * Body text and addresses are never printed to stdout (totals only).
 *
 * Re-running is not expected (one-off). If a vendor domain is later attached to a row that
 * was already inserted as unassigned, use "取り込む" (Import) on the settings page
 * (re-running leaves vendor_news orphaned, referring to a new mail_id).
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import PostalMime from 'postal-mime'

import { toJstDateKey } from '../src/lib/jst.ts'
import { splitForwardedBlock } from '../src/lib/mail/forwarded.ts'
import { matchVendorByDomain } from '../src/lib/mail/match.ts'
import { splitMbox } from '../src/lib/mail/mbox.ts'
import { extractBody, toParsedMail } from '../src/lib/mail/parse.ts'
import { inboundToNews } from '../src/lib/mail/toNews.ts'
import { sqlString } from './lib/seed.mjs'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')

type VendorRow = { id: string; name: string; news_email_domain: string | null }

function parseArgs(argv: string[]): { mbox: string; vendors: string } {
  const mbox = argv.find((a) => !a.startsWith('--'))
  const vi = argv.indexOf('--vendors')
  const vendors = vi >= 0 ? argv[vi + 1] : undefined
  if (!mbox || !vendors) {
    console.error('usage: tsx scripts/import-mbox.ts <mail.mbox> --vendors <vendors.json>')
    process.exit(1)
  }
  return { mbox: resolve(root, mbox), vendors: resolve(root, vendors) }
}

function loadVendors(path: string): { id: string; name: string; newsEmailDomain: string | null }[] {
  const json = JSON.parse(readFileSync(path, 'utf8')) as { results?: VendorRow[] }[] | VendorRow[]
  const rows: VendorRow[] =
    Array.isArray(json) && json.length > 0 && 'results' in json[0]
      ? (json as { results?: VendorRow[] }[]).flatMap((r) => r.results ?? [])
      : (json as VendorRow[])
  return rows.map((r) => ({ id: r.id, name: r.name, newsEmailDomain: r.news_email_domain }))
}

async function main() {
  const { mbox, vendors: vendorsPath } = parseArgs(process.argv.slice(2))
  const vendors = loadVendors(vendorsPath)
  // Read as latin1 (1 byte = 1 code unit): an mbox can contain 8-bit bodies such as
  // Shift_JIS as is, and reading it as utf8 corrupts them beyond recovery.
  // The separator ('From ' line) is ASCII, so splitting on the string is correct, and each
  // message is turned back into bytes with Buffer.from(part, 'latin1') and passed to
  // postal-mime (charset interpretation is left to postal-mime).
  const messages = splitMbox(readFileSync(mbox, 'latin1'))
  const nowIso = new Date().toISOString()
  const receivedOn = toJstDateKey(nowIso)

  // Do not add BEGIN TRANSACTION / COMMIT: `wrangler d1 execute --file` already runs the
  // whole file atomically, so adding transaction statements causes a "started a transaction
  // inside a transaction" error (as in the Cloudflare D1 import procedure).
  const lines: string[] = ['-- generated by scripts/import-mbox.ts']
  const perVendor = new Map<string, number>()
  let unassigned = 0
  let withEvent = 0

  for (const raw of messages) {
    const email = await PostalMime.parse(Buffer.from(raw, 'latin1'))
    const parsed = await toParsedMail(email)
    // The mbox is the user's own Takeout (trusted input), so build the body unconditionally
    // (the Worker side calls it only after authorization passes. See extractBody in
    // src/lib/mail/parse.ts)
    const body = extractBody(email)
    let fromAddress = parsed.from
    let subject = parsed.subject
    let sentOn = parsed.date ? toJstDateKey(parsed.date) : null
    let bodyText = body.text
    const block = splitForwardedBlock(body.text)
    if (block) {
      fromAddress = block.from ?? fromAddress
      subject = block.subject ?? subject
      sentOn = block.date ?? sentOn
      bodyText = block.body
    }
    // NUL cannot go into SQLite TEXT (sqlite3_bind_text cuts at NUL), so strip it
    subject = subject.replace(/\0/g, '')
    // Same as above (body)
    bodyText = bodyText.replace(/\0/g, '')
    const vendor = matchVendorByDomain(fromAddress, vendors)
    const mailId = crypto.randomUUID()
    const status = vendor ? 'imported' : 'unassigned'
    let newsId: string | null = null
    let newsSql: string | null = null
    let newsUrl: string | null = null
    if (vendor) {
      const draft = inboundToNews(
        { messageId: parsed.messageId, subject, text: bodyText, sentOn },
        vendor.id,
        receivedOn,
      )
      newsId = crypto.randomUUID()
      newsUrl = draft.url
      newsSql =
        `INSERT INTO vendor_news (id, vendor_id, url, title, summary, published_on, event_start, event_end, event_kind, mail_id) VALUES (` +
        [
          newsId,
          draft.vendorId,
          draft.url,
          draft.title,
          draft.summary,
          draft.publishedOn,
          draft.eventStart,
          draft.eventEnd,
          draft.eventKind,
          mailId,
        ]
          .map(sqlString)
          .join(', ') +
        `) ON CONFLICT(url) DO NOTHING;`
      perVendor.set(vendor.name, (perVendor.get(vendor.name) ?? 0) + 1)
      if (draft.eventStart) withEvent++
    } else {
      unassigned++
    }
    lines.push(
      `INSERT INTO inbound_mails (id, message_id, received_at, from_address, forwarded_by, subject, sent_on, body_text, body_truncated, status, reject_reason, vendor_id, news_id, created_at, updated_at) VALUES (` +
        [
          mailId,
          parsed.messageId,
          nowIso,
          fromAddress,
          'mbox',
          subject,
          sentOn,
          bodyText,
          body.truncated ? 1 : 0,
          status,
          null,
          vendor?.id ?? null,
          // news_id is NULL at this point. It is set by UPDATE after the vendor_news INSERT
          // (inbound_mails.news_id -> vendor_news and vendor_news.mail_id -> inbound_mails
          // are mutual FKs, so inserting news_id first rolls back everything on an FK violation)
          null,
          nowIso,
          nowIso,
        ]
          .map(sqlString)
          .join(', ') +
        `) ON CONFLICT(message_id) DO NOTHING;`,
    )
    if (newsSql && newsId) {
      lines.push(newsSql)
      // Even when a re-run made vendor_news DO NOTHING, look up the existing id by url and link it
      lines.push(
        `UPDATE inbound_mails SET news_id = (SELECT id FROM vendor_news WHERE url = ${sqlString(newsUrl)}) WHERE id = ${sqlString(mailId)} AND news_id IS NULL;`,
      )
    }
  }

  const out = resolve(root, 'seed.local/out/mails.sql')
  mkdirSync(dirname(out), { recursive: true })
  writeFileSync(out, lines.join('\n') + '\n')

  console.log(`mails: ${messages.length} → ${out}`)
  for (const [name, n] of perVendor) console.log(`  ${name}: ${n}`)
  console.log(`  unassigned: ${unassigned}`)
  console.log(`  with event date: ${withEvent}`)
  console.log('next: npx wrangler d1 execute sumai-log --remote --file seed.local/out/mails.sql')
}

main().catch((e) => {
  console.error(e instanceof Error ? e.message : String(e))
  process.exit(1)
})
