/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as MapRouteImport } from './routes/map'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiGeocodeRouteImport } from './routes/api.geocode'
import { Route as PlacesIdRouteImport } from './routes/places.$id'
import { Route as ApiPhotosSplatRouteImport } from './routes/api.photos.$'
import { Route as CandidatesPropertiesIdRouteImport } from './routes/candidates_.properties.$id'
import { Route as CandidatesVendorsIdRouteImport } from './routes/candidates_.vendors.$id'
import { Route as RecordsVisitsIdRouteImport } from './routes/records_.visits.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeocodeRoute = ApiGeocodeRouteImport.update({
  id: '/api/geocode',
  path: '/api/geocode',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesIdRoute = PlacesIdRouteImport.update({
  id: '/places/$id',
  path: '/places/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPhotosSplatRoute = ApiPhotosSplatRouteImport.update({
  id: '/api/photos/$',
  path: '/api/photos/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesPropertiesIdRoute = CandidatesPropertiesIdRouteImport.update({
  id: '/candidates_/properties/$id',
  path: '/candidates/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesVendorsIdRoute = CandidatesVendorsIdRouteImport.update({
  id: '/candidates_/vendors/$id',
  path: '/candidates/vendors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsVisitsIdRoute = RecordsVisitsIdRouteImport.update({
  id: '/records_/visits/$id',
  path: '/records/visits/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/candidates': typeof CandidatesRoute
  '/map': typeof MapRoute
  '/records': typeof RecordsRoute
  '/settings': typeof SettingsRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/places/$id': typeof PlacesIdRoute
  '/api/photos/$': typeof ApiPhotosSplatRoute
  '/candidates/properties/$id': typeof CandidatesPropertiesIdRoute
  '/candidates/vendors/$id': typeof CandidatesVendorsIdRoute
  '/records/visits/$id': typeof RecordsVisitsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/candidates': typeof CandidatesRoute
  '/map': typeof MapRoute
  '/records': typeof RecordsRoute
  '/settings': typeof SettingsRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/places/$id': typeof PlacesIdRoute
  '/api/photos/$': typeof ApiPhotosSplatRoute
  '/candidates/properties/$id': typeof CandidatesPropertiesIdRoute
  '/candidates/vendors/$id': typeof CandidatesVendorsIdRoute
  '/records/visits/$id': typeof RecordsVisitsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/candidates': typeof CandidatesRoute
  '/map': typeof MapRoute
  '/records': typeof RecordsRoute
  '/settings': typeof SettingsRoute
  '/api/geocode': typeof ApiGeocodeRoute
  '/places/$id': typeof PlacesIdRoute
  '/api/photos/$': typeof ApiPhotosSplatRoute
  '/candidates_/properties/$id': typeof CandidatesPropertiesIdRoute
  '/candidates_/vendors/$id': typeof CandidatesVendorsIdRoute
  '/records_/visits/$id': typeof RecordsVisitsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/candidates'
    | '/map'
    | '/records'
    | '/settings'
    | '/api/geocode'
    | '/places/$id'
    | '/api/photos/$'
    | '/candidates/properties/$id'
    | '/candidates/vendors/$id'
    | '/records/visits/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/candidates'
    | '/map'
    | '/records'
    | '/settings'
    | '/api/geocode'
    | '/places/$id'
    | '/api/photos/$'
    | '/candidates/properties/$id'
    | '/candidates/vendors/$id'
    | '/records/visits/$id'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/candidates'
    | '/map'
    | '/records'
    | '/settings'
    | '/api/geocode'
    | '/places/$id'
    | '/api/photos/$'
    | '/candidates_/properties/$id'
    | '/candidates_/vendors/$id'
    | '/records_/visits/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  CandidatesRoute: typeof CandidatesRoute
  MapRoute: typeof MapRoute
  RecordsRoute: typeof RecordsRoute
  SettingsRoute: typeof SettingsRoute
  ApiGeocodeRoute: typeof ApiGeocodeRoute
  PlacesIdRoute: typeof PlacesIdRoute
  ApiPhotosSplatRoute: typeof ApiPhotosSplatRoute
  CandidatesPropertiesIdRoute: typeof CandidatesPropertiesIdRoute
  CandidatesVendorsIdRoute: typeof CandidatesVendorsIdRoute
  RecordsVisitsIdRoute: typeof RecordsVisitsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geocode': {
      id: '/api/geocode'
      path: '/api/geocode'
      fullPath: '/api/geocode'
      preLoaderRoute: typeof ApiGeocodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$id': {
      id: '/places/$id'
      path: '/places/$id'
      fullPath: '/places/$id'
      preLoaderRoute: typeof PlacesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/photos/$': {
      id: '/api/photos/$'
      path: '/api/photos/$'
      fullPath: '/api/photos/$'
      preLoaderRoute: typeof ApiPhotosSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates_/properties/$id': {
      id: '/candidates_/properties/$id'
      path: '/candidates/properties/$id'
      fullPath: '/candidates/properties/$id'
      preLoaderRoute: typeof CandidatesPropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates_/vendors/$id': {
      id: '/candidates_/vendors/$id'
      path: '/candidates/vendors/$id'
      fullPath: '/candidates/vendors/$id'
      preLoaderRoute: typeof CandidatesVendorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records_/visits/$id': {
      id: '/records_/visits/$id'
      path: '/records/visits/$id'
      fullPath: '/records/visits/$id'
      preLoaderRoute: typeof RecordsVisitsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  CandidatesRoute: CandidatesRoute,
  MapRoute: MapRoute,
  RecordsRoute: RecordsRoute,
  SettingsRoute: SettingsRoute,
  ApiGeocodeRoute: ApiGeocodeRoute,
  PlacesIdRoute: PlacesIdRoute,
  ApiPhotosSplatRoute: ApiPhotosSplatRoute,
  CandidatesPropertiesIdRoute: CandidatesPropertiesIdRoute,
  CandidatesVendorsIdRoute: CandidatesVendorsIdRoute,
  RecordsVisitsIdRoute: RecordsVisitsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
